import TextSplitAnimation from "@/src/components/TextAnimation";
import Head from "next/head";
import AISpeechC from "@/src/components/common-partials/AiSpeech";

export default function AISpeech() {
  return (
    <>
      <Head>
        <title>AI Speech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-10">
        <TextSplitAnimation className="text-6xl text-white uppercase text-center">
          Спілкуйся з AI
        </TextSplitAnimation>
        <AISpeechC></AISpeechC>
      </div>
    </>
  );
}
