import Head from 'next/head';
import Heading from '@/components/Heading';

export default function Search() {
  return (
    <>
      <Head>
        <title>Search Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Heading text="Hello from search page"></Heading>
    </>
  )
}