import Head from "next/head";
// components
import TextSplitAnimation from "@/src/components/TextAnimation";

export default function Search() {
  return (
    <>
      <Head>
        <title>Search page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-10">
        <TextSplitAnimation as="h1" size="h1" className="font-normal">
          Search Page
        </TextSplitAnimation>
        <TextSplitAnimation as="p" className="font-normal m-auto">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem amet
          tempore maxime eius expedita porro consectetur quia sequi! Rem facilis
          iure eveniet at laborum nulla maxime veniam nesciunt sapiente
          possimus!
        </TextSplitAnimation>
        <TextSplitAnimation className="m-auto" size="p-sm" as="p">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid
          dignissimos dolorem mollitia velit delectus aut ipsa tenetur est. Nam
          sequi soluta dolor, molestiae adipisci voluptatum ad quo doloribus
          quas ipsam?
        </TextSplitAnimation>
      </div>
    </>
  );
}
